languageCode: "en-us"
baseUrl: "https://dimalip.in/"
Title: "Dima Lipin"
theme: "anubis"
paginate: 10
disqusShortname: yourdiscussshortname
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 1


params:
  author: "Dima Lipin"
  represent: "Dima Lipin. Machine Learning Engineer. Hacker."
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  tabTitle: "Dima Lipin's Personal Website"


markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown