languageCode: "en-us"
baseUrl: "https://dimalip.in/"
Title: "Dima Lipin"
theme: "anubis"
paginate: 10
googleAnalytics: UA-171403903-1
enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 10
  - identifier: privacy
    name: Privacy
#    title: Privacy Policy
    url: /privacy_policy/
    weight: 1


params:
  author: "Dima Lipin"
  represent: "Dima Lipin. Machine Learning Engineer. Hacker."
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  dateFormat: "2 Jan 06"
  paginationSinglePost: true
  title: "Dima Lipin's Personal Website"

privacy:
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown