languageCode: "en-us"
baseUrl: "https://www.dimalip.in/"
title: "Dima Lipin"
theme: "anubis"
paginate: 10
disqusShortname: yourdiscussshortname
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 1


params:
  author: ""
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown